# Generated by Django 2.1.5 on 2019-02-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddVehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=10)),
                ('vehicle_insurance_dt', models.DateField()),
                ('vehicle_fc_dt', models.DateField()),
                ('vehicle_chasis_number', models.CharField(max_length=32)),
                ('vehicle_engine_number', models.CharField(max_length=32)),
            ],
        ),
    ]
